export { createBarracks } from "./barracks";
export { createFactory } from "./factory";
export { createHelipad } from "./helipad";
export { createDepot } from "./depot";
export { createResearchLab } from "./researchLab";
export { createPlatform } from "./platform";
export { createTurret } from "./turret";
export type { BuildingHandle, BuildingKind } from "./types";
export type { ResearchLabHandle } from "./researchLab";
export type { PlatformHandle } from "./platform";
export type { TurretHandle } from "./turret";
